//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AccreditMsg.proto
// Note: requires additional types generated from: ChatData.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccreditReq")]
  public partial class AccreditReq : global::ProtoBuf.IExtensible
  {
    public AccreditReq() {}
    

    private string _accreditCode = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accreditCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accreditCode
    {
      get { return _accreditCode; }
      set { _accreditCode = value; }
    }
    private string _accreditMac;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accreditMac", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accreditMac
    {
      get { return _accreditMac; }
      set { _accreditMac = value; }
    }
    private protocol.AccreditReq.Type _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.AccreditReq.Type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _userId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private protocol.AccreditReq.DeviceType _deviceType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"deviceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.AccreditReq.DeviceType deviceType
    {
      get { return _deviceType; }
      set { _deviceType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AGREE", Value=0)]
      AGREE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DISAGREE", Value=1)]
      DISAGREE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQUIRE", Value=2)]
      REQUIRE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ONLYONETIME", Value=3)]
      ONLYONETIME = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"DeviceType")]
    public enum DeviceType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOBILE", Value=0)]
      MOBILE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PC", Value=1)]
      PC = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccreditRsp")]
  public partial class AccreditRsp : global::ProtoBuf.IExtensible
  {
    public AccreditRsp() {}
    
    private protocol.AccreditRsp.ResultCode _resultCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.AccreditRsp.ResultCode resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ResultCode")]
    public enum ResultCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=1)]
      FAIL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESPONSCODE", Value=2)]
      RESPONSCODE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CANLOGIN", Value=3)]
      CANLOGIN = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}