//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AddFriendMsg.proto
// Note: requires additional types generated from: UserData.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddFriendReq")]
  public partial class AddFriendReq : global::ProtoBuf.IExtensible
  {
    public AddFriendReq() {}
    
    private string _friendUserId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"friendUserId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string friendUserId
    {
      get { return _friendUserId; }
      set { _friendUserId = value; }
    }

    private protocol.AddFriendReq.RequestType _requestType = protocol.AddFriendReq.RequestType.REQUEST;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"requestType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(protocol.AddFriendReq.RequestType.REQUEST)]
    public protocol.AddFriendReq.RequestType requestType
    {
      get { return _requestType; }
      set { _requestType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RequestType")]
    public enum RequestType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQUEST", Value=0)]
      REQUEST = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AGREE", Value=1)]
      AGREE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REFUSE", Value=2)]
      REFUSE = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddFriendRsp")]
  public partial class AddFriendRsp : global::ProtoBuf.IExtensible
  {
    public AddFriendRsp() {}
    
    private protocol.AddFriendRsp.ResultCode _resultCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.AddFriendRsp.ResultCode resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }

    private protocol.UserItem _user = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocol.UserItem user
    {
      get { return _user; }
      set { _user = value; }
    }

    private protocol.AddFriendRsp.RequestType _requestType = protocol.AddFriendRsp.RequestType.REQUEST;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"requestType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(protocol.AddFriendRsp.RequestType.REQUEST)]
    public protocol.AddFriendRsp.RequestType requestType
    {
      get { return _requestType; }
      set { _requestType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ResultCode")]
    public enum ResultCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=1)]
      FAIL = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RequestType")]
    public enum RequestType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQUEST", Value=0)]
      REQUEST = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AGREE", Value=1)]
      AGREE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REFUSE", Value=2)]
      REFUSE = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}