//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AddFileMsg.proto
// Note: requires additional types generated from: FileData.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddFileReq")]
  public partial class AddFileReq : global::ProtoBuf.IExtensible
  {
    public AddFileReq() {}
    

    private int _fileId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fileId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fileId
    {
      get { return _fileId; }
      set { _fileId = value; }
    }
    private string _fileName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fileName
    {
      get { return _fileName; }
      set { _fileName = value; }
    }

    private string _fileInfo = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"fileInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fileInfo
    {
      get { return _fileInfo; }
      set { _fileInfo = value; }
    }

    private string _fileSize = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fileSize", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fileSize
    {
      get { return _fileSize; }
      set { _fileSize = value; }
    }

    private string _fileDate = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fileDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fileDate
    {
      get { return _fileDate; }
      set { _fileDate = value; }
    }
    private string _userId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private string _fileUrl = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fileUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fileUrl
    {
      get { return _fileUrl; }
      set { _fileUrl = value; }
    }

    private string _filePwd = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"filePwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string filePwd
    {
      get { return _filePwd; }
      set { _filePwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddFileRsp")]
  public partial class AddFileRsp : global::ProtoBuf.IExtensible
  {
    public AddFileRsp() {}
    
    private protocol.AddFileRsp.ResultCode _resultCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.AddFileRsp.ResultCode resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }
    private string _fileName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fileName
    {
      get { return _fileName; }
      set { _fileName = value; }
    }

    private string _fileInfo = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"fileInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fileInfo
    {
      get { return _fileInfo; }
      set { _fileInfo = value; }
    }

    private string _fileSize = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fileSize", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fileSize
    {
      get { return _fileSize; }
      set { _fileSize = value; }
    }

    private string _fileDate = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fileDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fileDate
    {
      get { return _fileDate; }
      set { _fileDate = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ResultCode")]
    public enum ResultCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=1)]
      FAIL = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}