//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FileData.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileItem")]
  public partial class FileItem : global::ProtoBuf.IExtensible
  {
    public FileItem() {}
    

    private string _fileId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fileId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fileId
    {
      get { return _fileId; }
      set { _fileId = value; }
    }
    private string _fileName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fileName
    {
      get { return _fileName; }
      set { _fileName = value; }
    }

    private string _fileInfo = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"fileInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fileInfo
    {
      get { return _fileInfo; }
      set { _fileInfo = value; }
    }

    private string _fileSize = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fileSize", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fileSize
    {
      get { return _fileSize; }
      set { _fileSize = value; }
    }

    private string _fileDate = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fileDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fileDate
    {
      get { return _fileDate; }
      set { _fileDate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}