//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GetFileInfoMsg.proto
// Note: requires additional types generated from: FileData.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetFileInfoReq")]
  public partial class GetFileInfoReq : global::ProtoBuf.IExtensible
  {
    public GetFileInfoReq() {}
    
    private string _fileId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fileId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fileId
    {
      get { return _fileId; }
      set { _fileId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetFileInfoRsp")]
  public partial class GetFileInfoRsp : global::ProtoBuf.IExtensible
  {
    public GetFileInfoRsp() {}
    
    private protocol.GetFileInfoRsp.ResultCode _resultCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.GetFileInfoRsp.ResultCode resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }
    private protocol.FileItem _fileItem;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fileItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protocol.FileItem fileItem
    {
      get { return _fileItem; }
      set { _fileItem = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ResultCode")]
    public enum ResultCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=1)]
      FAIL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FILE_NOT_EXIST", Value=2)]
      FILE_NOT_EXIST = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}