//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
   
// Generated from: HolePunchMsg.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HolePunchReq")]
  public partial class HolePunchReq : global::ProtoBuf.IExtensible
  {
    public HolePunchReq() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private protocol.HolePunchReq.RequstType _requstType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"requstType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.HolePunchReq.RequstType requstType
    {
      get { return _requstType; }
      set { _requstType = value; }
    }
    private string _command;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"command", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string command
    {
      get { return _command; }
      set { _command = value; }
    }
    private string _sendId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sendId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sendId
    {
      get { return _sendId; }
      set { _sendId = value; }
    }
    private string _receiveId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"receiveId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string receiveId
    {
      get { return _receiveId; }
      set { _receiveId = value; }
    }
    private string _fileSize;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"fileSize", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fileSize
    {
      get { return _fileSize; }
      set { _fileSize = value; }
    }

    private string _fileDate = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fileDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fileDate
    {
      get { return _fileDate; }
      set { _fileDate = value; }
    }

    private string _filePath = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"filePath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string filePath
    {
      get { return _filePath; }
      set { _filePath = value; }
    }

    private string _fileTempName = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"fileTempName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fileTempName
    {
      get { return _fileTempName; }
      set { _fileTempName = value; }
    }

    private string _fileType = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"fileType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fileType
    {
      get { return _fileType; }
      set { _fileType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RequstType")]
    public enum RequstType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND", Value=0)]
      SEND = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RECEIVE", Value=1)]
      RECEIVE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER", Value=2)]
      SERVER = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HolePunchRsp")]
  public partial class HolePunchRsp : global::ProtoBuf.IExtensible
  {
    public HolePunchRsp() {}
    
    private protocol.HolePunchRsp.ResponsType _responsType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"responsType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.HolePunchRsp.ResponsType responsType
    {
      get { return _responsType; }
      set { _responsType = value; }
    }
    private protocol.HolePunchRsp.ResultCode _resultCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.HolePunchRsp.ResultCode resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }

    private string _ip = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }

    private protocol.HolePunchRsp.FailReason _failReason = protocol.HolePunchRsp.FailReason.NOSUCHFILE;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"failReason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(protocol.HolePunchRsp.FailReason.NOSUCHFILE)]
    public protocol.HolePunchRsp.FailReason failReason
    {
      get { return _failReason; }
      set { _failReason = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ResponsType")]
    public enum ResponsType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND", Value=0)]
      SEND = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RECEIVE", Value=1)]
      RECEIVE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER", Value=2)]
      SERVER = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ResultCode")]
    public enum ResultCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=1)]
      FAIL = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"FailReason")]
    public enum FailReason
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOSUCHFILE", Value=0)]
      NOSUCHFILE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FILEEXIST", Value=1)]
      FILEEXIST = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER", Value=2)]
      OTHER = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}