//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LoginMsg.proto
// Note: requires additional types generated from: UserData.proto
// Note: requires additional types generated from: ChatData.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginReq")]
  public partial class LoginReq : global::ProtoBuf.IExtensible
  {
    public LoginReq() {}
    

    private string _userId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private string _userPassword = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userPassword", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userPassword
    {
      get { return _userPassword; }
      set { _userPassword = value; }
    }

    private protocol.LoginReq.LoginType _loginType = protocol.LoginReq.LoginType.MOBILE;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"loginType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(protocol.LoginReq.LoginType.MOBILE)]
    public protocol.LoginReq.LoginType loginType
    {
      get { return _loginType; }
      set { _loginType = value; }
    }

    private string _userMac = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"userMac", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userMac
    {
      get { return _userMac; }
      set { _userMac = value; }
    }

    private string _mobileInfo = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"mobileInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mobileInfo
    {
      get { return _mobileInfo; }
      set { _mobileInfo = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"LoginType")]
    public enum LoginType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOBILE", Value=0)]
      MOBILE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PC", Value=1)]
      PC = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRsp")]
  public partial class LoginRsp : global::ProtoBuf.IExtensible
  {
    public LoginRsp() {}
    
    private protocol.LoginRsp.ResultCode _resultCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.LoginRsp.ResultCode resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }
    private readonly global::System.Collections.Generic.List<protocol.UserItem> _userItem = new global::System.Collections.Generic.List<protocol.UserItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"userItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protocol.UserItem> userItem
    {
      get { return _userItem; }
    }
  
    private readonly global::System.Collections.Generic.List<protocol.ChatItem> _chatItem = new global::System.Collections.Generic.List<protocol.ChatItem>();
    [global::ProtoBuf.ProtoMember(3, Name=@"chatItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protocol.ChatItem> chatItem
    {
      get { return _chatItem; }
    }
  

    private string _userMac = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"userMac", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userMac
    {
      get { return _userMac; }
      set { _userMac = value; }
    }
    private protocol.LoginRsp.MainMobileCode _mainMobileCode;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mainMobileCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.LoginRsp.MainMobileCode mainMobileCode
    {
      get { return _mainMobileCode; }
      set { _mainMobileCode = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ResultCode")]
    public enum ResultCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGGEDIN", Value=1)]
      LOGGEDIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=2)]
      FAIL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTMAINPHONE", Value=3)]
      NOTMAINPHONE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAINPHONEOUTLINE", Value=4)]
      MAINPHONEOUTLINE = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MainMobileCode")]
    public enum MainMobileCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"YES", Value=0)]
      YES = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO", Value=1)]
      NO = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}