//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MiracastData.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MiracastItem")]
  public partial class MiracastItem : global::ProtoBuf.IExtensible
  {
    public MiracastItem() {}
    
    private string _manufactory;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"manufactory", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string manufactory
    {
      get { return _manufactory; }
      set { _manufactory = value; }
    }
    private string _appname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"appname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string appname
    {
      get { return _appname; }
      set { _appname = value; }
    }
    private string _packagename;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"packagename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string packagename
    {
      get { return _packagename; }
      set { _packagename = value; }
    }
    private string _model;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"model", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string model
    {
      get { return _model; }
      set { _model = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}