//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PersonalSettingsMsg.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PersonalSettingsReq")]
  public partial class PersonalSettingsReq : global::ProtoBuf.IExtensible
  {
    public PersonalSettingsReq() {}
    

    private string _userName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }

    private string _userPassword = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userPassword", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userPassword
    {
      get { return _userPassword; }
      set { _userPassword = value; }
    }

    private int _headIndex = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"headIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int headIndex
    {
      get { return _headIndex; }
      set { _headIndex = value; }
    }

    private int _code = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }

    private string _userOldPassword = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"userOldPassword", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userOldPassword
    {
      get { return _userOldPassword; }
      set { _userOldPassword = value; }
    }

    private string _userAddress = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"userAddress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userAddress
    {
      get { return _userAddress; }
      set { _userAddress = value; }
    }

    private string _userStreet = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"userStreet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userStreet
    {
      get { return _userStreet; }
      set { _userStreet = value; }
    }

    private string _userCommunity = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"userCommunity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userCommunity
    {
      get { return _userCommunity; }
      set { _userCommunity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PersonalSettingsRsp")]
  public partial class PersonalSettingsRsp : global::ProtoBuf.IExtensible
  {
    public PersonalSettingsRsp() {}
    
    private protocol.PersonalSettingsRsp.ResultCode _resultCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.PersonalSettingsRsp.ResultCode resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }
    private protocol.PersonalSettingsRsp.ChangeType _changeType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"changeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.PersonalSettingsRsp.ChangeType changeType
    {
      get { return _changeType; }
      set { _changeType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ResultCode")]
    public enum ResultCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=1)]
      FAIL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OLDPASSWORDWRONG", Value=2)]
      OLDPASSWORDWRONG = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ChangeType")]
    public enum ChangeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NAME", Value=0)]
      NAME = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PASSWORD", Value=1)]
      PASSWORD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADDRESS", Value=2)]
      ADDRESS = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}