//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProgressData.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProgressItem")]
  public partial class ProgressItem : global::ProtoBuf.IExtensible
  {
    public ProgressItem() {}
    
    private string _fileName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fileName
    {
      get { return _fileName; }
      set { _fileName = value; }
    }
    private string _progress;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"progress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string progress
    {
      get { return _progress; }
      set { _progress = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}