//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RegisterMsg.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterReq")]
  public partial class RegisterReq : global::ProtoBuf.IExtensible
  {
    public RegisterReq() {}
    
    private protocol.RegisterReq.RequestCode _requestCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"requestCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.RegisterReq.RequestCode requestCode
    {
      get { return _requestCode; }
      set { _requestCode = value; }
    }

    private string _userId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private string _userName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }

    private string _userPassword = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"userPassword", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userPassword
    {
      get { return _userPassword; }
      set { _userPassword = value; }
    }

    private string _userMobile = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"userMobile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userMobile
    {
      get { return _userMobile; }
      set { _userMobile = value; }
    }

    private string _userMac = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"userMac", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userMac
    {
      get { return _userMac; }
      set { _userMac = value; }
    }

    private string _userAddress = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"userAddress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userAddress
    {
      get { return _userAddress; }
      set { _userAddress = value; }
    }

    private string _userStreet = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"userStreet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userStreet
    {
      get { return _userStreet; }
      set { _userStreet = value; }
    }

    private string _userCommunity = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"userCommunity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userCommunity
    {
      get { return _userCommunity; }
      set { _userCommunity = value; }
    }

    private int _registerCode = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"registerCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int registerCode
    {
      get { return _registerCode; }
      set { _registerCode = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RequestCode")]
    public enum RequestCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHECKUSERID", Value=0)]
      CHECKUSERID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHECKMOBILE", Value=1)]
      CHECKMOBILE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REGISTER", Value=2)]
      REGISTER = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterRsp")]
  public partial class RegisterRsp : global::ProtoBuf.IExtensible
  {
    public RegisterRsp() {}
    
    private protocol.RegisterRsp.ResultCode _resultCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.RegisterRsp.ResultCode resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }
    private protocol.RegisterRsp.ResultType _resultType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"resultType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.RegisterRsp.ResultType resultType
    {
      get { return _resultType; }
      set { _resultType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ResultType")]
    public enum ResultType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"USERID", Value=0)]
      USERID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOBILE", Value=1)]
      MOBILE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REGISTER", Value=2)]
      REGISTER = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ResultCode")]
    public enum ResultCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXIST", Value=1)]
      EXIST = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CODEWRONG", Value=2)]
      CODEWRONG = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}