//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SendCode.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendCodeSync")]
  public partial class SendCodeSync : global::ProtoBuf.IExtensible
  {
    public SendCodeSync() {}
    
    private protocol.SendCodeSync.ChangeType _changeType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"changeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.SendCodeSync.ChangeType changeType
    {
      get { return _changeType; }
      set { _changeType = value; }
    }

    private string _mobile = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mobile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mobile
    {
      get { return _mobile; }
      set { _mobile = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ChangeType")]
    public enum ChangeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PASSWORD", Value=0)]
      PASSWORD = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REGISTER", Value=1)]
      REGISTER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOBILE", Value=2)]
      MOBILE = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}