//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: UserData.proto
// Note: requires additional types generated from: FileData.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserItem")]
  public partial class UserItem : global::ProtoBuf.IExtensible
  {
    public UserItem() {}
    
    private string _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _userName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }

    private int _headIndex = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"headIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int headIndex
    {
      get { return _headIndex; }
      set { _headIndex = value; }
    }

    private int _fileNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fileNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fileNum
    {
      get { return _fileNum; }
      set { _fileNum = value; }
    }

    private bool _isFriend = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isFriend", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isFriend
    {
      get { return _isFriend; }
      set { _isFriend = value; }
    }

    private bool _isOnline = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"isOnline", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isOnline
    {
      get { return _isOnline; }
      set { _isOnline = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}